export const defaultNervosDaoInfo: State.NervosDao = {
  totalDeposit: '',
  depositorsCount: '',
  depositChanges: '',
  unclaimedCompensationChanges: '',
  claimedCompensationChanges: '',
  depositorChanges: '',
  unclaimedCompensation: '',
  claimedCompensation: '',
  averageDepositTime: '',
  miningReward: '',
  depositCompensation: '',
  treasuryAmount: '',
  estimatedApc: '',
}
