[default.extend-words]
# ordinal suffix
st='st'
nd='nd'
rd='rd'
th='th'
# typo in api, should be fixed later
toekn='toekn'
# echart config
metalness = 'metalness'

[files]
extend-exclude=["*.test.*"]
