const initStatisticChartsState: State.StatisticChartsState = {
  statisticDifficultyHashRates: [],
  statisticHashRates: [],
  statisticUncleRates: [],
  statisticDifficulties: [],
  statisticAddressCounts: [],
  statisticCellCounts: [],
  statisticDifficultyUncleRates: [],
  statisticTotalDaoDeposits: [],
  statisticNewDaoDeposits: [],
  statisticNewDaoWithdraw: [],
  statisticTransactionCounts: [],
  statisticAddressBalanceRanks: [],
  statisticBalanceDistributions: [],
  statisticTxFeeHistories: [],
  statisticBlockTimeDistributions: [],
  statisticAverageBlockTimes: [],
  statisticOccupiedCapacities: [],
  statisticEpochTimeDistributions: [],
  statisticCirculationRatios: [],
  statisticNewNodeCounts: [],
  statisticNodeDistributions: [],
}

export default initStatisticChartsState
