const initStatisticChartsState: State.StatisticChartsState = {
  statisticTotalDaoDeposits: [],
  statisticTotalDaoDepositsFetchEnd: false,
  statisticNewDaoDeposits: [],
  statisticNewDaoDepositsFetchEnd: false,
  statisticNewDaoWithdraw: [],
  statisticNewDaoWithdrawFetchEnd: false,
  statisticCirculationRatios: [],
  statisticCirculationRatiosFetchEnd: false,
  statisticNewNodeCounts: [],
  statisticNewNodeCountsFetchEnd: false,
  statisticNodeDistributions: [],
  statisticNodeDistributionsFetchEnd: false,
  statisticTotalSupplies: [],
  statisticTotalSuppliesFetchEnd: false,
  statisticAnnualPercentageCompensations: [],
  statisticAnnualPercentageCompensationsFetchEnd: false,
  statisticSecondaryIssuance: [],
  statisticSecondaryIssuanceFetchEnd: false,
  statisticInflationRates: [],
  statisticInflationRatesFetchEnd: false,
  statisticLiquidity: [],
  statisticLiquidityFetchEnd: false,
}

export default initStatisticChartsState
