const initStatisticChartsState: State.StatisticChartsState = {
  statisticCellCounts: [],
  statisticCellCountsFetchEnd: false,
  statisticTotalDaoDeposits: [],
  statisticTotalDaoDepositsFetchEnd: false,
  statisticNewDaoDeposits: [],
  statisticNewDaoDepositsFetchEnd: false,
  statisticNewDaoWithdraw: [],
  statisticNewDaoWithdrawFetchEnd: false,
  statisticTransactionCounts: [],
  statisticTransactionCountsFetchEnd: false,
  statisticBalanceDistributions: [],
  statisticBalanceDistributionsFetchEnd: false,
  statisticTxFeeHistories: [],
  statisticTxFeeHistoriesFetchEnd: false,
  statisticBlockTimeDistributions: [],
  statisticBlockTimeDistributionsFetchEnd: false,
  statisticAverageBlockTimes: [],
  statisticAverageBlockTimesFetchEnd: false,
  statisticOccupiedCapacities: [],
  statisticOccupiedCapacitiesFetchEnd: false,
  statisticEpochTimeDistributions: [],
  statisticEpochTimeDistributionsFetchEnd: false,
  statisticCirculationRatios: [],
  statisticCirculationRatiosFetchEnd: false,
  statisticNewNodeCounts: [],
  statisticNewNodeCountsFetchEnd: false,
  statisticNodeDistributions: [],
  statisticNodeDistributionsFetchEnd: false,
  statisticTotalSupplies: [],
  statisticTotalSuppliesFetchEnd: false,
  statisticAnnualPercentageCompensations: [],
  statisticAnnualPercentageCompensationsFetchEnd: false,
  statisticSecondaryIssuance: [],
  statisticSecondaryIssuanceFetchEnd: false,
  statisticInflationRates: [],
  statisticInflationRatesFetchEnd: false,
  statisticLiquidity: [],
  statisticLiquidityFetchEnd: false,
}

export default initStatisticChartsState
